install_arm_toolchain: $(MARKER)
	@bash $(CURDIR)/scripts/install_arm_toolchain.sh


install_qemu_arm: $(MARKER)
	@bash $(CURDIR)/scripts/install_qemu_arm.sh

setup_idf: $(MARKER)
	@bash $(CURDIR)/scripts/setup_idf.sh

setup_mbed: $(MARKER)
	@bash $(CURDIR)/scripts/setup_mbed.sh

setup_node: $(MARKER)
	@bash $(CURDIR)/scripts/setup_node.sh

setup_rust: $(MARKER)
	@bash $(CURDIR)/scripts/setup_rust.sh

libs_mbed: $(MARKER)
	@bash $(CURDIR)/scripts/libs_mbed.sh

